source("Initialize.R")
source("Universe.R")
source("BBGData.R")
Universe <- Universe.Historical(as.Date("2017-01-10"))
PX_LAST <- BBGData.Load("PX_LAST","2016")
CHG_PCT <- BBGData.Load("CHG_PCT","2016")
SH_OUT <- BBGData.Load("SH_OUT","2016")
PX_VOL <- BBGData.Load("PX_VOL","2016")

TOT_ASSET <- BBGData.Load("TOT_ASSET","2016")
BOOk_VAL <- BBGData.Load("BOOk_VAL","2016")
DEBT <- BBGData.Load("DEBT","2016")
EV <- BBGData.Load("EV","2016")